### ISSUE TITLE
IBT4ZWAVE used to work with Gen5 and not working with ZooZ stick

### ISSUE THREAD

**Issue by xabix** [AlCalzone/node-zwave-js#7130]
Hello All,

The inclusion was done OK and the device is correctly added (and ping works and the interview too). But action like open or close don't work.

![Screenshot 2024-08-28 at 15 20 57](https://github.com/user-attachments/assets/a1b66eec-e18c-410c-bf02-659ad4e61dea)

Is the device supported with the ZooZ stick, is it a pb of a firmware?

I see messages like:
- [Application Status CC (not implemented)]
- no handler for application command
- [Multilevel Switch] duration: "unknown" => "unknown"

Here is the log:
[Zwave.log](https://github.com/user-attachments/files/16784049/Zwave.log)
[Zwave-silly.log](https://github.com/user-attachments/files/16784119/Zwave-silly.log)

Thanks
XabiX

Version:
zwave-js-ui: 9.17.0zwave-js: 13.1.0home id: 3886169917home hex: 0xe7a23f3d

**Comment by AlCalzone** [comment]
This is not an issue with the stick - it is "just" a radio for the most part. Issues with that device have been reported before, but AFAIK there has never been a solution or an answer what's going on.

After trying to control the device, it sends back an Application Status CC, with the Application Rejected Request command. This CC is not understood by Z-Wave JS, but typically means "can't do that". In this case the device actively responded that it won't execute the request.

Maybe the motor is jammed? Maybe it needs to be calibrated?
Can you try using the "start/stop level change" controls to open/close it without setting a specific position?

**Comment by xabix** [comment]
Hi @AlCalzone 

What I don't understand is why he used to work with the same installation and Gen5 stick. If I understood you the good news is that if he used to work, he should still be working.

I did a manual calibration, and try to push for a level change to 40
![Screenshot 2024-08-29 at 10 53 50](https://github.com/user-attachments/assets/d808b0a2-bcaa-4c31-a2ad-7399c009c63c)

Here is the log:
[ZM.log](https://github.com/user-attachments/files/16796373/ZM.log)

Should I look to make a level calibration directly from the Zwave/stick?

Thanks
XabiX

PS: https://www.niceforyou.com/sites/default/files/upload/manuals/idv01mm_en.pdf

**Comment by AlCalzone** [comment]
Can you share a log of you controlling the device with the Gen5 stick then?

**Comment by xabix** [comment]
Sorry I don't have it anymore. I could find a backup of the Gen5 stick if that works (before I did upgrade it and brick it). Then I was so piece off that I bought a new stick as after the upgrade I couldn't get it working again (and I don't have a windows machine that is not virtualized to make proper stick upgrades).

What if I re-interview the device in silly mode with the ZooZ, could the interview process help understanding is the items were correctly 'created'?

**Comment by AlCalzone** [comment]
I see, that sounds like a hurdle. You could also contact the manufacturer and ask why the device responds with a **Application Status CC, with the Application Rejected Request command**.

Re-interviewing doesn't make sense  in this case.

**Comment by xabix** [comment]
Do we know if the module is supposed to work? What I mean is the issue specific to me (could I have break/brick the device?) or all folks are having issues with this device?

It seems that it's working for some people, so I will search if this is linked to a device fw issue and yes will try to open a case with them then?
https://community.home-assistant.io/t/zwave-gate-module-nice-ibt4zwave/221803

it's supposed to be supported:
[OpenSmartHouse Z-Wave Device Database 29](https://opensmarthouse.org/zwavedatabase/1320)

**Comment by AlCalzone** [comment]
It's working for some people. I can't tell you why yours isn't working, other than it refuses to react to controlling commands. Your best bet is to ask the manufacturer, they should be able to tell you.

**Comment by mariusz-schimke** [comment]
If it may help in any way, I can add that it does work fine with my Zooz controller. The only two differences I can spot are:
* Zooz firmware version,
* My IBT4ZWAVE module couldn't be added securely.

Also, my network is on the EU radio bands, if it may matter (I noticed some differences in the FW version availability for Zooz based on the region).

<img width="1049" alt="Zrzut ekranu 2024-09-18 o 14 42 34" src="https://github.com/user-attachments/assets/07a4ee10-bd53-4b5c-9ff4-e3511c2026a7">
<img width="925" alt="Zrzut ekranu 2024-09-18 o 14 42 08" src="https://github.com/user-attachments/assets/a0ac3b11-2a67-4962-8ea3-d01a3157db98">

**Comment by xabix** [comment]
I did try with 1.5 and now 1.6 with EU bands (having done a re-interview) too but when I press 8-38-0 Start to open nothing happens.

<img width="2213" height="401" alt="Image" src="https://github.com/user-attachments/assets/fdae9242-f3c9-4e71-9933-ec5ce7360e0a" />

Is there anything I can do to understand why it s not working?

<img width="1989" height="821" alt="Image" src="https://github.com/user-attachments/assets/97efd9fa-cd15-43d6-b7a0-f250be628be9" />
<img width="1707" height="180" alt="Image" src="https://github.com/user-attachments/assets/3ad070b6-9280-4b3c-b6f2-f1e3de83d50a" />
<img width="1924" height="637" alt="Image" src="https://github.com/user-attachments/assets/3764a3a2-1d85-4c8f-b356-290e1a08ba81" />

BTW I don't have permissions, to re open the issue, so maybe I need to recreate one?

**Comment by xabix** [comment]
```

2025-07-30 16:44:58.020 DRIVER « [RES] [GetBackgroundRSSI]
                                   channel 0: -95 dBm
                                   channel 1: -99 dBm
                                   channel 2: -99 dBm
                                   channel 3: -93 dBm
2025-07-30 16:44:58.020 DRIVER   all queues idle
2025-07-30 16:45:00.452 INFO APP: GET /health/zwave 301 0.339 ms - 162
2025-07-30 16:45:02.951 INFO APP: GET / 304 0.691 ms - -
2025-07-30 16:45:02.958 INFO APP: GET /assets/index-C0J8C5tA.js 304 0.418 ms - -
2025-07-30 16:45:02.959 INFO APP: GET /assets/index-DFE8u6UB.css 304 0.244 ms - -
2025-07-30 16:45:03.040 INFO APP: GET /assets/Login-D1DEPZ6p.js 304 0.666 ms - -
2025-07-30 16:45:03.041 INFO APP: GET /assets/Login-Mxccy4LS.css 304 1.198 ms - -
2025-07-30 16:45:03.043 INFO APP: GET /api/auth-enabled 304 0.806 ms - -
2025-07-30 16:45:03.064 INFO APP: GET /assets/ControlPanel-CYtsXyQL.js 304 0.491 ms - -
2025-07-30 16:45:03.103 INFO APP: GET /logo.svg 304 0.330 ms - -
2025-07-30 16:45:03.106 DEBUG SOCKET: New connection UfJYMeK5MI-DzB84AAAN
2025-07-30 16:45:03.111 INFO APP: GET /assets/MaterialIcons-Regular-DOtZ65Va.woff2 304 0.321 ms - -
2025-07-30 16:45:03.114 DEBUG SOCKET: Event INITED emitted to UfJYMeK5MI-DzB84AAAN
2025-07-30 16:45:04.134 INFO APP: GET /api/settings 304 1028.841 ms - -
2025-07-30 16:45:04.151 INFO APP: GET /api/auth-enabled 304 0.772 ms - -
2025-07-30 16:45:04.164 INFO APP: GET /assets/StatisticsCard-BRCMD4vb.js 304 1.718 ms - -
2025-07-30 16:45:04.166 INFO APP: GET /assets/index-DNTi1ph1.js 304 0.331 ms - -
2025-07-30 16:45:04.168 INFO APP: GET /assets/index-C1PWt9Gl.css 304 1.054 ms - -
2025-07-30 16:45:04.168 INFO APP: GET /assets/DialogAdvanced-D5KZ1_3L.css 304 1.540 ms - -
2025-07-30 16:45:04.169 INFO APP: GET /assets/colors-o-D5abqK.js 304 1.957 ms - -
2025-07-30 16:45:04.171 INFO APP: GET /assets/DialogAdvanced-Bg0uGpMh.js 304 0.341 ms - -
2025-07-30 16:45:04.172 INFO APP: GET /assets/vuedraggable.umd-Dx4O7qjJ.js 304 0.483 ms - -
2025-07-30 16:45:04.191 INFO APP: GET /assets/RichValue-20fg0Ggl.js 304 0.597 ms - -
2025-07-30 16:45:04.193 INFO APP: GET /assets/ReinterviewBadge-DGIK8j4v.js 304 0.491 ms - -
2025-07-30 16:45:04.196 INFO APP: GET /assets/RichValue-D2CNQpme.css 304 0.765 ms - -
2025-07-30 16:45:04.198 INFO APP: GET /assets/StatisticsArrows-DSfLXZYi.js 304 1.213 ms - -
2025-07-30 16:45:04.198 INFO APP: GET /assets/ExpandedNode-Cz-LXYo1.css 304 1.123 ms - -
2025-07-30 16:45:04.200 INFO APP: GET /assets/ExpandedNode-DiF8lCfQ.js 304 0.472 ms - -
2025-07-30 16:45:04.201 INFO APP: GET /assets/ColumnFilter-BQquroMO.js 304 0.479 ms - -
2025-07-30 16:45:04.225 INFO APP: GET /assets/BlinkIcon-DCHomnKQ.js 304 0.437 ms - -
2025-07-30 16:45:04.241 INFO APP: GET /assets/ColumnFilterNumber-CsIRBHrc.js 304 0.364 ms - -
2025-07-30 16:45:04.244 INFO APP: GET /assets/ColumnFilterString-KCPd2KgN.js 304 0.436 ms - -
2025-07-30 16:45:04.246 INFO APP: GET /assets/ColumnFilterBoolean-9FKpQmze.js 304 1.098 ms - -
2025-07-30 16:45:04.249 INFO APP: GET /assets/ColumnFilterDate-u036HQQK.js 304 1.332 ms - -
2025-07-30 16:45:08.931 INFO APP: GET /assets/NodeDetails-CJiT9Mva.js 304 0.707 ms - -
2025-07-30 16:45:08.931 INFO APP: GET /assets/NodeDetails-BVv96O7e.css 304 1.268 ms - -
2025-07-30 16:45:08.934 INFO APP: GET /assets/AssociationGroups-CP7hRCYJ.js 304 1.024 ms - -
2025-07-30 16:45:08.936 INFO APP: GET /assets/OTAUpdates-PF-Xz_8y.js 304 2.315 ms - -
2025-07-30 16:45:08.978 INFO APP: GET /assets/ValueId-N27pO7iR.css 304 0.629 ms - -
2025-07-30 16:45:08.979 INFO APP: GET /assets/ValueId-DAwLSamn.js 304 1.089 ms - -
2025-07-30 16:45:12.381 DEBUG SOCKET: Event ZWAVE_API emitted to UfJYMeK5MI-DzB84AAAN
2025-07-30 16:45:12.382 INFO Z-WAVE: Calling api writeValue with args: [
  { nodeId: 8, commandClass: 38, endpoint: 0, property: 'Open' },
  true,
  null,
  [length]: 3
]
2025-07-30 16:45:12.382 INFO Z-WAVE: Writing true to 8-38-0-Open
2025-07-30 16:45:12.383 CNTRLR   [Node 008] [setValue] calling SET_VALUE API MultilevelSwitchCCAPI:
                                   property:     Open
                                   property key: undefined
                                   optimistic:   true
2025-07-30 16:45:12.384 DRIVER   one or more queues busy
2025-07-30 16:45:12.386 DRIVER » [Node 008] [REQ] [SendDataBridge]
                                 │ source node id:   1
                                 │ transmit options: 0x25
                                 │ callback id:      51
                                 └─[Security2CCNonceGet]
                                     sequence number: 35
2025-07-30 16:45:12.386 SERIAL » 0x011100a900010008039f0123250000000033e6                            (19 bytes)
2025-07-30 16:45:12.390 SERIAL « [ACK]                                                                   (0x06)
2025-07-30 16:45:12.394 SERIAL « 0x010401a90152                                                       (6 bytes)
2025-07-30 16:45:12.395 SERIAL » [ACK]                                                                   (0x06)
2025-07-30 16:45:12.396 DRIVER « [RES] [SendDataBridge]
                                   was sent: true
2025-07-30 16:45:12.406 SERIAL « 0x011d00a93300000100a47f7f7f7f00000300000000030100007f7f7f7f7fa3    (31 bytes)
2025-07-30 16:45:12.407 SERIAL » [ACK]                                                                   (0x06)
2025-07-30 16:45:12.407 DRIVER « [REQ] [SendDataBridge]
                                   callback id:            51
                                   transmit status:        OK, took 10 ms
                                   routing attempts:       1
                                   protocol & route speed: Z-Wave, 100 kbit/s
                                   routing scheme:         LWR
                                   ACK RSSI:               -92 dBm
                                   ACK channel no.:        0
                                   TX channel no.:         0
2025-07-30 16:45:12.415 SERIAL « 0x012200a80000010008149f0299019737b19dfbb257dffe643a1acc49e3b400a40 (36 bytes)
                                 07f7fec
2025-07-30 16:45:12.415 SERIAL » [ACK]                                                                   (0x06)
2025-07-30 16:45:12.416 DRIVER « [Node 008] [REQ] [BridgeApplicationCommand]
                                 │ RSSI: -92 dBm
                                 └─[Security2CCNonceReport]
                                     sequence number:  153
                                     SOS:              true
                                     MOS:              false
                                     receiver entropy: 0x9737b19dfbb257dffe643a1acc49e3b4
2025-07-30 16:45:12.418 DRIVER » [Node 008] [REQ] [SendDataBridge]
                                 │ source node id:   1
                                 │ transmit options: 0x25
                                 │ callback id:      52
                                 └─[Security2CCMessageEncapsulation]
                                   │ sequence number: 36
                                   │ extensions:
                                   │ · type: SPAN
                                   │   sender EI: 0x63837b2a48fb94e23d6ebfa69d315db1
                                   └─[MultilevelSwitchCCStartLevelChange]
                                       startLevel: 0 (ignored)
                                       direction:  up
2025-07-30 16:45:12.418 SERIAL » 0x013100a900010008239f032401124163837b2a48fb94e23d6ebfa69d315db1386 (51 bytes)
                                 dbd742c7d5015dd7db2333225000000003453
2025-07-30 16:45:12.427 SERIAL « [ACK]                                                                   (0x06)
2025-07-30 16:45:12.432 SERIAL « 0x010401a90152                                                       (6 bytes)
2025-07-30 16:45:12.433 SERIAL » [ACK]                                                                   (0x06)
2025-07-30 16:45:12.434 DRIVER « [RES] [SendDataBridge]
                                   was sent: true
2025-07-30 16:45:12.448 SERIAL « 0x011d00a93400000100a57f7f7f7f00000300000000030100007f7f7f7f7fa5    (31 bytes)
2025-07-30 16:45:12.448 SERIAL » [ACK]                                                                   (0x06)
2025-07-30 16:45:12.449 DRIVER « [REQ] [SendDataBridge]
                                   callback id:            52
                                   transmit status:        OK, took 10 ms
                                   routing attempts:       1
                                   protocol & route speed: Z-Wave, 100 kbit/s
                                   routing scheme:         LWR
                                   ACK RSSI:               -91 dBm
                                   ACK channel no.:        0
                                   TX channel no.:         0
2025-07-30 16:45:12.464 SERIAL « 0x011d00a800000100080f9f039a00dbcbb16c57ef43c8b64eab00a4007f7f43    (31 bytes)
2025-07-30 16:45:12.465 SERIAL » [ACK]                                                                   (0x06)
2025-07-30 16:45:12.466 DRIVER « [Node 008] [REQ] [BridgeApplicationCommand]
                                 │ RSSI: -92 dBm
                                 └─[Security2CCMessageEncapsulation]
                                   │ sequence number: 154
                                   │ security class:  S2_Authenticated
                                   └─[Application Status CC (not implemented)]
                                       command: 0x02
                                       payload: 0x00
2025-07-30 16:45:12.466 CNTRLR « [Node 008] TODO: no handler for application command
2025-07-30 16:45:12.951 CNTRLR   [Node 008] [setValue] result of SET_VALUE API call for MultilevelSwitchCCAPI: 
                                 undefined
2025-07-30 16:45:12.952 CNTRLR   [Node 008] [setValue] updating value with event
2025-07-30 16:45:12.952 CNTRLR   [Node 008] [translateValueEvent: value updated]
                                   commandClass: Multilevel Switch
                                   endpoint:     0
                                   property:     Open
                                   propertyKey:  undefined
                                   internal:     false
                                   secret:       false
                                   event source: driver
2025-07-30 16:45:12.952 CNTRLR   [Node 008] [translateValueEvent: value updated]
                                   is root endpoint:        true
                                   is application CC:       true
                                   should hide root values: false
2025-07-30 16:45:12.953 INFO Z-WAVE: [Node 008] Value updated: 38-0-Open false => true
2025-07-30 16:45:12.953 INFO Z-WAVE: Success zwave api call writeValue { status: 254 }
2025-07-30 16:45:12.954 DRIVER   all queues idle

```

**Comment by xabix** [comment]
Thanks @AlCalzone, I hope we will find the issue 👍 

I am sorry if I am lost but it's been more than a year that I am trying to make my device work with my stick and I am not sure where to look at stick vs device vs config

I do see this messages:
[Node 008] TODO: no handler for application command

I tried to override the CC of this device with a devices.json file in config and store directories but it doesn't seem to help neither:
<img width="701" height="826" alt="Image" src="https://github.com/user-attachments/assets/e3cb228c-dccf-4de2-bf4c-b2df31dd12e3" />

at the end the issue is just that I can't open or close the gate through Zwave

The log: [z-ui_2025-07-31.log](https://github.com/user-attachments/files/21525488/z-ui_2025-07-31.log)

zwave-js-ui: 10.11.0 zwave-js: 15.10.0
home id: 3886169917 home hex: 0xe7a23f3d
Home Assistant OS: Core 2025.7.4, Supervisor 2025.07.2, OS 16.0, Frontend 20250702.3
Zooz  ZST39 800 LR v1.60 EU with 7.23.2 SDK

Some links that I checked:
[IBT4ZWAVE Not working with zwave-js-ui: 9.9.0 and zwave-js: 12.4.4](https://github.com/zwave-js/zwave-js/issues/6693)
[Improve handling of unknown (254) values](https://github.com/zwave-js/zwave-js/issues/5864)
[Z-WAVE Device configuration file not recognized](https://community.home-assistant.io/t/z-wave-device-configuration-file-not-recognized/877602)
[zwave product documentation](https://devices.zwave-js.io/?jumpTo=0x0441:0x2400:0x1000:0.0)

**Comment by AlCalzone** [comment]
```
2025-07-30 16:45:12.466 DRIVER « [Node 008] [REQ] [BridgeApplicationCommand]
                                 │ RSSI: -92 dBm
                                 └─[Security2CCMessageEncapsulation]
                                   │ sequence number: 154
                                   │ security class:  S2_Authenticated
                                   └─[Application Status CC (not implemented)]
                                       command: 0x02
                                       payload: 0x00

```
This is what the device sends in response you controlling it with the `StartLevelChange` command. Z-Wave JS doesn't understand this yet, which is related to https://github.com/zwave-js/zwave-js/issues/7956, but it means the device did not accept the command.
I don't know why - this device's implementation seems to be somewhat peculiar - but it seems like it claims to support Multilevel Switch command class version 4, but does not implement some of its functionality.

You should be able to control the device by setting the target value to 99 to open or 0 to close.

Not sure why you weren't seeing the issue on the other stick, as that has nothing to do with it - it's just a transmitter/receiver.

**Comment by xabix** [comment]
If I set target value to 99, the gate doesn't move. Is it the same issue or a different one that is not dependant to the transmitter/receiver?

```
2025-07-31 14:27:42.725 INFO Z-WAVE: Writing 99 to 8-38-0-targetValue
2025-07-31 14:27:42.725 CNTRLR   [Node 008] [setValue] calling SET_VALUE API MultilevelSwitchCCAPI:
                                   property:     targetValue
                                   property key: undefined
                                   optimistic:   true
2025-07-31 14:27:42.727 DRIVER   one or more queues busy
2025-07-31 14:27:42.728 DRIVER » [Node 008] [REQ] [SendDataBridge]
                                 │ source node id:   1
                                 │ transmit options: 0x25
                                 │ callback id:      89
                                 └─[Security2CCNonceGet]
                                     sequence number: 206
2025-07-31 14:27:42.729 SERIAL » 0x011100a900010008039f01ce25000000005961                            (19 bytes)
2025-07-31 14:27:42.733 SERIAL « [ACK]                                                                   (0x06)
2025-07-31 14:27:42.736 SERIAL « 0x010401a90152                                                       (6 bytes)
2025-07-31 14:27:42.736 SERIAL » [ACK]                                                                   (0x06)
2025-07-31 14:27:42.737 DRIVER « [RES] [SendDataBridge]
                                   was sent: true
2025-07-31 14:27:42.750 SERIAL « 0x011d00a95900000100a07f7f7f7f00000300000000030100007f7f7f7f7fcd    (31 bytes)
2025-07-31 14:27:42.750 SERIAL » [ACK]                                                                   (0x06)
2025-07-31 14:27:42.751 DRIVER « [REQ] [SendDataBridge]
                                   callback id:            89
                                   transmit status:        OK, took 10 ms
                                   routing attempts:       1
                                   protocol & route speed: Z-Wave, 100 kbit/s
                                   routing scheme:         LWR
                                   ACK RSSI:               -96 dBm
                                   ACK channel no.:        0
                                   TX channel no.:         0
2025-07-31 14:27:42.798 SERIAL « 0x012200a80000010008149f028201a682a221e0bfd77c9530b321d2414ad600a00 (36 bytes)
                                 07f7fbd
2025-07-31 14:27:42.799 SERIAL » [ACK]                                                                   (0x06)
2025-07-31 14:27:42.800 DRIVER « [Node 008] [REQ] [BridgeApplicationCommand]
                                 │ RSSI: -96 dBm
                                 └─[Security2CCNonceReport]
                                     sequence number:  130
                                     SOS:              true
                                     MOS:              false
                                     receiver entropy: 0xa682a221e0bfd77c9530b321d2414ad6
2025-07-31 14:27:42.802 DRIVER » [Node 008] [REQ] [SendDataBridge]
                                 │ source node id:   1
                                 │ transmit options: 0x25
                                 │ callback id:      90
                                 └─[Security2CCMessageEncapsulation]
                                   │ sequence number: 207
                                   │ extensions:
                                   │ · type: SPAN
                                   │   sender EI: 0xa19d3663391bb77948345e98b36df6dc
                                   └─[MultilevelSwitchCCSet]
                                       target value: 99
2025-07-31 14:27:42.802 SERIAL » 0x013000a900010008229f03cf011241a19d3663391bb77948345e98b36df6dc288 (50 bytes)
                                 0ab6f5adc955acc97f53d25000000005a4e
2025-07-31 14:27:42.811 SERIAL « [ACK]                                                                   (0x06)
2025-07-31 14:27:42.813 SERIAL « 0x010401a90152                                                       (6 bytes)
2025-07-31 14:27:42.814 SERIAL » [ACK]                                                                   (0x06)
2025-07-31 14:27:42.814 DRIVER « [RES] [SendDataBridge]
                                   was sent: true
2025-07-31 14:27:42.860 SERIAL « 0x011d00a95a00000400a07f7f7f7f00000300000000030200007f7f7f7f7fc8    (31 bytes)
2025-07-31 14:27:42.861 SERIAL » [ACK]                                                                   (0x06)
2025-07-31 14:27:42.861 DRIVER « [REQ] [SendDataBridge]
                                   callback id:            90
                                   transmit status:        OK, took 40 ms
                                   routing attempts:       2
                                   protocol & route speed: Z-Wave, 100 kbit/s
                                   routing scheme:         LWR
                                   ACK RSSI:               -96 dBm
                                   ACK channel no.:        0
                                   TX channel no.:         0
2025-07-31 14:27:42.900 SERIAL « 0x011d00a800000100080f9f0383004f60b576ed1866118925e7009f007f7fe9    (31 bytes)
2025-07-31 14:27:42.901 SERIAL » [ACK]                                                                   (0x06)
2025-07-31 14:27:42.901 DRIVER « [Node 008] [REQ] [BridgeApplicationCommand]
                                 │ RSSI: -97 dBm
                                 └─[Security2CCMessageEncapsulation]
                                   │ sequence number: 131
                                   │ security class:  S2_Authenticated
                                   └─[Application Status CC (not implemented)]
                                       command: 0x02
                                       payload: 0x00
2025-07-31 14:27:42.902 CNTRLR « [Node 008] TODO: no handler for application command
2025-07-31 14:27:43.363 CNTRLR   [Node 008] [setValue] result of SET_VALUE API call for MultilevelSwitchCCAPI: 
                                 undefined
2025-07-31 14:27:43.364 CNTRLR   [Node 008] [setValue] updating value with event
2025-07-31 14:27:43.364 CNTRLR   [Node 008] [translateValueEvent: value updated]
                                   commandClass: Multilevel Switch
                                   endpoint:     0
                                   property:     targetValue
                                   propertyKey:  undefined
                                   internal:     false
                                   secret:       false
                                   event source: driver
2025-07-31 14:27:43.364 CNTRLR   [Node 008] [translateValueEvent: value updated]
                                   is root endpoint:        true
                                   is application CC:       true
                                   should hide root values: false
2025-07-31 14:27:43.365 INFO Z-WAVE: [Node 008] Value updated: 38-0-targetValue null => 99
2025-07-31 14:27:43.365 CNTRLR   [Node 008] [translateValueEvent: value updated]
                                   commandClass: Multilevel Switch
                                   endpoint:     0
                                   property:     currentValue
                                   propertyKey:  undefined
                                   internal:     false
                                   secret:       false
                                   event source: undefined
2025-07-31 14:27:43.366 CNTRLR   [Node 008] [~] [Multilevel Switch] currentValue: null => 99       [Endpoint 0]
2025-07-31 14:27:43.366 CNTRLR   [Node 008] [translateValueEvent: value updated]
                                   is root endpoint:        true
                                   is application CC:       true
                                   should hide root values: false
2025-07-31 14:27:43.366 INFO Z-WAVE: [Node 008] Value updated: 38-0-currentValue null => 99
2025-07-31 14:27:43.367 INFO Z-WAVE: Success zwave api call writeValue { status: 254 }
2025-07-31 14:27:43.368 DRIVER   all queues idle
2025-07-31 14:27:48.369 DRIVER   one or more queues busy
2025-07-31 14:27:48.370 DRIVER » [Node 008] [REQ] [SendDataBridge]
                                 │ source node id:   1
                                 │ transmit options: 0x25
                                 │ callback id:      91
                                 └─[Security2CCMessageEncapsulation]
                                   │ sequence number: 208
                                   └─[MultilevelSwitchCCGet]
2025-07-31 14:27:48.371 SERIAL » 0x011c00a9000100080e9f03d0000b01469d03653dfafbbc25000000005b48      (30 bytes)
2025-07-31 14:27:48.376 SERIAL « [ACK]                                                                   (0x06)
2025-07-31 14:27:48.379 SERIAL « 0x010401a90152                                                       (6 bytes)
2025-07-31 14:27:48.379 SERIAL » [ACK]                                                                   (0x06)
2025-07-31 14:27:48.379 DRIVER « [RES] [SendDataBridge]
                                   was sent: true
2025-07-31 14:27:48.393 SERIAL « 0x011d00a95b00000100a07f7f7f7f00000300000000030100007f7f7f7f7fcf    (31 bytes)
2025-07-31 14:27:48.393 SERIAL » [ACK]                                                                   (0x06)
2025-07-31 14:27:48.393 DRIVER « [REQ] [SendDataBridge]
                                   callback id:            91
                                   transmit status:        OK, took 10 ms
                                   routing attempts:       1
                                   protocol & route speed: Z-Wave, 100 kbit/s
                                   routing scheme:         LWR
                                   ACK RSSI:               -96 dBm
                                   ACK channel no.:        0
                                   TX channel no.:         0
2025-07-31 14:27:48.471 SERIAL « 0x011f00a80000010008119f038400f16a7d3b4049b82e8c5771f9bf00a0007f7f4 (33 bytes)
                                 6
2025-07-31 14:27:48.473 SERIAL » [ACK]                                                                   (0x06)
2025-07-31 14:27:48.473 CNTRLR   [Node 008] [translateValueEvent: value updated]
                                   commandClass: Multilevel Switch
                                   endpoint:     0
                                   property:     currentValue
                                   propertyKey:  undefined
                                   internal:     false
                                   secret:       false
                                   event source: undefined
2025-07-31 14:27:48.474 CNTRLR   [Node 008] [~] [Multilevel Switch] currentValue: 99 => null       [Endpoint 0]
2025-07-31 14:27:48.474 CNTRLR   [Node 008] [translateValueEvent: value updated]
                                   is root endpoint:        true
                                   is application CC:       true
                                   should hide root values: false
2025-07-31 14:27:48.474 INFO Z-WAVE: [Node 008] Value updated: 38-0-currentValue 99 => null
2025-07-31 14:27:48.474 CNTRLR   [Node 008] [translateValueEvent: value updated]
                                   commandClass: Multilevel Switch
                                   endpoint:     0
                                   property:     duration
                                   propertyKey:  undefined
                                   internal:     false
                                   secret:       false
                                   event source: undefined
2025-07-31 14:27:48.474 CNTRLR   [Node 008] [~] [Multilevel Switch] duration: "unknown" => "unknow [Endpoint 0]
                                 n"
2025-07-31 14:27:48.474 CNTRLR   [Node 008] [translateValueEvent: value updated]
                                   is root endpoint:        true
                                   is application CC:       true
                                   should hide root values: false
2025-07-31 14:27:48.475 INFO Z-WAVE: [Node 008] Value updated: 38-0-duration unknown => unknown
2025-07-31 14:27:48.475 CNTRLR   [Node 008] [translateValueEvent: value updated]
                                   commandClass: Multilevel Switch
                                   endpoint:     0
                                   property:     targetValue
                                   propertyKey:  undefined
                                   internal:     false
                                   secret:       false
                                   event source: undefined
2025-07-31 14:27:48.475 CNTRLR   [Node 008] [~] [Multilevel Switch] targetValue: 99 => null        [Endpoint 0]
2025-07-31 14:27:48.475 CNTRLR   [Node 008] [translateValueEvent: value updated]
                                   is root endpoint:        true
                                   is application CC:       true
                                   should hide root values: false
2025-07-31 14:27:48.475 INFO Z-WAVE: [Node 008] Value updated: 38-0-targetValue 99 => null
2025-07-31 14:27:48.476 DRIVER « [Node 008] [REQ] [BridgeApplicationCommand]
                                 │ RSSI: -96 dBm
                                 └─[Security2CCMessageEncapsulation]
                                   │ sequence number: 132
                                   │ security class:  S2_Authenticated
                                   └─[MultilevelSwitchCCReport]
                                       current value: unknown
                                       target value:  unknown
                                       duration:      unknown
```

**Comment by AlCalzone** [comment]
Same issue. It's as if the device is in a state where it cannot move.

**Comment by xabix** [comment]
Thanks AlCalzone!

I have attached for reference a debug log including the interview and both attempts: Open cmd and Target Value 99.
[z-ui_2025-07-31 (interview & Open & TV 99).log](https://github.com/user-attachments/files/21530765/z-ui_2025-07-31.interview.Open.TV.99.log)

I will try to execute a learning cycle on the gate while the device is plugged to see if that states for the device changes some how and things start to work.

Could there be an issue of the signal strengh? I assume I don't need the config/devices.json override and I should remove it as it's not the route to go to find a workaround and be able to force the opening/closing.

**Comment by AlCalzone** [comment]
It's not a communication issue. The device receives the command just fine and then refuses to do it. I'm pretty sure it is something with the device, maybe even a physical issue.
